-- Idempotent Emporion purchases for the Triarchs of Olympus website.
--
-- 002 already made a double purchase impossible: `player_purchases` is unique
-- on (user_id, item_id), the balance is locked before it is checked, and
-- purchase_shop_item is the only path by which Favour may fall. That is enough
-- for the game, whose store is a single desktop panel.
--
-- A web page is a rougher environment. A double-click, an impatient refresh, a
-- flaky mobile connection that retries a POST — each can deliver the same
-- intent twice. Under 002 the second delivery returns `already_owned`, which is
-- technically correct and reads to the player as a failure ("did it work?").
--
-- So this migration adds an OVERLOAD that takes a caller-generated request id
-- and remembers what that request decided. A retry replays the original
-- answer instead of producing a new one.
--
--   public.purchase_shop_item(p_item_id text)                 -- 002, untouched
--   public.purchase_shop_item(p_item_id text, p_request_id uuid)  -- new
--
-- The game calls the one-argument form and is completely unaffected: the old
-- function is neither dropped nor redefined here. PostgreSQL resolves the two
-- by arity, and the new form delegates to the old one, so there is exactly one
-- implementation of the actual purchase rules and no chance of the two drifting
-- apart.
--
-- CONCURRENCY. Two simultaneous deliveries of the same request id race to
-- insert the same (user_id, request_id). The winner proceeds; the loser's
-- `on conflict do update` blocks on the winner's uncommitted row, and when the
-- winner commits, the loser reads back the stored result and returns it. So a
-- double-click cannot buy twice, cannot report a spurious `already_owned`, and
-- cannot see a half-finished state. The disabled button in the UI is a
-- courtesy; this is the guarantee.

create table if not exists public.shop_purchase_requests (
    request_row_id bigint generated always as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    -- Generated by the client. Only ever used as an idempotency token, scoped
    -- to the user, so a guessed or reused value from another account is
    -- meaningless.
    request_id uuid not null,

    item_id text not null,

    -- The outcome the first delivery produced, replayed verbatim to retries.
    result jsonb,

    created_at timestamptz not null default timezone('utc', now()),
    settled_at timestamptz,

    constraint shop_purchase_requests_unique
        unique (user_id, request_id)
);

create index if not exists shop_purchase_requests_purge_idx
on public.shop_purchase_requests (created_at);

alter table public.shop_purchase_requests enable row level security;

revoke all on table public.shop_purchase_requests from anon, authenticated;

-- No policies. The client never reads or writes this table directly; it only
-- ever sees the jsonb the function hands back.

comment on table public.shop_purchase_requests is
'Idempotency record for website Emporion purchases. One row per (player, request id); a retry replays the stored result instead of buying again.';


create or replace function public.purchase_shop_item(
    p_item_id    text,
    p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_row     public.shop_purchase_requests%rowtype;
    v_result  jsonb;
begin
    if v_user_id is null then
        return jsonb_build_object('ok', false, 'error', 'not_authenticated');
    end if;

    if p_request_id is null then
        return jsonb_build_object('ok', false, 'error', 'request_id_required');
    end if;

    -- Claim the request id. The DO UPDATE is a deliberate no-op write: it
    -- exists so that a concurrent duplicate BLOCKS here on the row lock rather
    -- than sailing past a DO NOTHING and running the purchase a second time.
    insert into public.shop_purchase_requests as r (user_id, request_id, item_id)
    values (v_user_id, p_request_id, p_item_id)
    on conflict (user_id, request_id) do update
        set item_id = r.item_id
    returning * into v_row;

    -- A settled row means this request already happened. Replay it, tagged so
    -- the UI can tell an original success from a retried one.
    if v_row.settled_at is not null then
        if v_row.item_id is distinct from p_item_id then
            -- Same token, different item: a client bug or a tampered replay.
            -- Refuse rather than silently buying the wrong thing.
            return jsonb_build_object('ok', false, 'error', 'request_id_reused');
        end if;

        return coalesce(v_row.result, jsonb_build_object('ok', false, 'error', 'temporary_failure'))
               || jsonb_build_object('duplicate', true);
    end if;

    -- First delivery. Everything below runs in this transaction, under the
    -- same locks 002 established.
    v_result := public.purchase_shop_item(p_item_id);

    update public.shop_purchase_requests
       set result     = v_result,
           settled_at = timezone('utc', now())
     where request_row_id = v_row.request_row_id;

    return v_result || jsonb_build_object('duplicate', false);
end;
$$;


-- Retention: an idempotency token is only useful for as long as a client might
-- retry with it. A day is generous; the purchase itself is permanent in
-- player_purchases regardless.
create or replace function public.purge_shop_purchase_requests()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_count integer;
begin
    delete from public.shop_purchase_requests r
     where r.created_at < timezone('utc', now()) - interval '24 hours';
    get diagnostics v_count = row_count;
    return v_count;
end;
$$;


revoke execute on function public.purchase_shop_item(text, uuid)
    from public, anon;

grant execute on function public.purchase_shop_item(text, uuid)
    to authenticated;

revoke execute on function public.purge_shop_purchase_requests()
    from public, anon, authenticated;

comment on function public.purchase_shop_item(text, uuid) is
'Idempotent wrapper around purchase_shop_item(text). Same rules, same locks, same atomicity; a retried request id replays its original outcome instead of buying again.';
